version: "3"


services:
  web:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_pomogutkids
    volumes:
      - .:/src
    ports:
      - "8200:8200"
    tty: true    
    command: ["sh", "-c", "python3 manage.py runserver 0.0.0.0:8200"]